version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ checksum "yarn.lock" }}
      - run:
          name: "ğŸ“¦ install"
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: node-{{ checksum "yarn.lock" }}
      - run:
          name: "ğŸ‘®ğŸ»â€â™‚ï¸ lint"
          command: "./ci/lint.sh"
      - run:
          name: "ğŸ›  build"
          command: "./ci/build.sh"
      - run:
          name: "ğŸ— provision"
          command: "./ci/provision.sh $environment"
      - run:
          name: "ğŸš€ deploy"
          command: "./ci/deploy.sh $environment"
