version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: ğŸ“¦ install
          command: yarn
      - run:
        name: ğŸ‘®ğŸ»â€â™‚ï¸ lint
        command: ./ci/lint.sh
      - run:
        name: ğŸ›  build
        command: ./ci/build.sh
      - run:
        name: ğŸ— provision
        command: ./ci/provision.sh $environment
      - run:
        name: ğŸš€ deploy
        command: ./ci/deploy.sh $environment
